spring:
  cloud:
    config:
      enabled: true
  datasource:
    initialization-mode: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: create-drop

server:
  port: 8080
      
ribbon:
  IsSecure: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
